# Generated by Django 6.1.1 on 2026-09-18 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorization_id', models.CharField(max_length=64)),
                ('source_authorization_id', models.CharField(blank=True, default='', max_length=64)),
                ('raw_event', models.JSONField()),
                ('simulated_purchased_at', models.DateTimeField()),
                ('deadline_at', models.DateTimeField()),
                ('received_at', models.DateTimeField()),
                ('billing_amount_chf', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Mandate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField()),
                ('hard_rules', models.JSONField(blank=True, default=list)),
                ('uncertainty_policy', models.CharField(choices=[('ask', 'Ask the customer'), ('decline', 'Decline'), ('approve', 'Approve')], default='ask', max_length=16)),
                ('guidance', models.JSONField(blank=True, default=list)),
                ('open_questions', models.JSONField(blank=True, default=list)),
                ('intent_spec', models.JSONField(blank=True, default=dict)),
                ('draft_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('mandate_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('revoked', 'Revoked')], default='draft', max_length=16)),
                ('confirmed_by', models.CharField(blank=True, default='', max_length=255)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approve', 'Approve'), ('decline', 'Decline'), ('step_up', 'Step up')], max_length=16)),
                ('reason_codes', models.JSONField(blank=True, default=list)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('customer_message', models.TextField(blank=True, default='')),
                ('engine_version', models.CharField(blank=True, default='', max_length=64)),
                ('is_final', models.BooleanField(default=True)),
                ('source', models.CharField(choices=[('engine', 'Automated engine decision'), ('customer', 'Customer step-up resolution')], default='engine', max_length=16)),
                ('forwarded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authorization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='api.authorizationrecord')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovedSpend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_chf', models.DecimalField(decimal_places=2, max_digits=12)),
                ('simulated_purchased_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('authorization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approved_spend', to='api.authorizationrecord')),
                ('mandate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_spends', to='api.mandate')),
            ],
            options={
                'ordering': ['-simulated_purchased_at'],
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(db_index=True, max_length=64)),
                ('scenario_id', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('event_counters', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mandate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='api.mandate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='authorizationrecord',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorizations', to='api.run'),
        ),
        migrations.AddConstraint(
            model_name='authorizationrecord',
            constraint=models.UniqueConstraint(fields=('run', 'authorization_id'), name='unique_authorization_per_run'),
        ),
    ]
